spring:
    datasource:
        url: jdbc:h2:file:C:\db\h2db
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        initialize: true
    jpa:
      hibernate.ddl-auto: validate
    activemq:
      in-memory: false
      pool.enabled: false
    h2.console.enabled: true
    thymeleaf.cache: false
        
flyway:
  clean-on-validation-error: true
  locations:
    - classpath:/db/migration