DROP SCHEMA IF EXISTS MAINTENANCE;
CREATE SCHEMA MAINTENANCE;

DROP SEQUENCE IF EXISTS MAINTENANCE.CONTRACT_REQUEST_ID;
CREATE SEQUENCE MAINTENANCE.CONTRACT_REQUEST_ID ;

CREATE TABLE MAINTENANCE.CONTRACT (
    CONTRACT_ID INTEGER NOT NULL ,
    CONTRACT_NAME NVARCHAR2(200) NOT NULL,
    FISCAL_YEAR INTEGER NOT NULL ,
    AMOUNT INTEGER NOT NULL,
    MAINTENANCE_RATE INTEGER NOT NULL,
    CONSTRAINT CONTRACT_PK PRIMARY KEY (
    CONTRACT_ID)
);

CREATE TABLE MAINTENANCE.PLAN (
    CONTRACT_ID INTEGER NOT NULL ,
    MONTH INTEGER NOT NULL,
    INSPECTION_POINT INTEGER NOT NULL
);

CREATE TABLE MAINTENANCE.SCHEDULE (
    CONTRACT_ID INTEGER NOT NULL ,
    MONTH INTEGER NOT NULL,
    DAY INTEGER NOT NULL,
);

INSERT INTO MAINTENANCE.CONTRACT (CONTRACT_ID, CONTRACT_NAME, FISCAL_YEAR, AMOUNT, MAINTENANCE_RATE) VALUES (1, '28年度保守契約', 28, 100000, 6);

INSERT INTO MAINTENANCE.PLAN (CONTRACT_ID, MONTH, INSPECTION_POINT) VALUES (1, 4, 1);
INSERT INTO MAINTENANCE.PLAN (CONTRACT_ID, MONTH, INSPECTION_POINT) VALUES (1, 4, 2);
INSERT INTO MAINTENANCE.PLAN (CONTRACT_ID, MONTH, INSPECTION_POINT) VALUES (1, 6, 3);
INSERT INTO MAINTENANCE.PLAN (CONTRACT_ID, MONTH, INSPECTION_POINT) VALUES (1, 8, 4);

INSERT INTO MAINTENANCE.SCHEDULE (CONTRACT_ID, MONTH, DAY) VALUES (1, 4, 10);